--- #YAML:1.0
name:                NetAddr-IP
version:             4.078
abstract:            Manages IPv4 and IPv6 addresses and subnets
license:             ~
author:              
    - Luis E. Muñoz <luismunoz@cpan.org>, Michael Robinton <miker@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
